# Generated by Django 5.2.9 on 2026-06-09 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_dns', '0030_dnsseckeytemplate_comments_dnsseckeytemplate_owner_and_more'),
        ('netbox_dns_bridge', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='integerkeyvaluesetting',
            options={},
        ),
        migrations.CreateModel(
            name='SeenTransferClients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('source_ip', models.GenericIPAddressField()),
                ('last_seen', models.DateTimeField()),
                ('view', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seen_transfer_clients', to='netbox_dns.view')),
            ],
            options={
                'ordering': ('source_ip',),
                'constraints': [models.UniqueConstraint(fields=('source_ip', 'view'), name='unique_ip_view_seen_client')],
            },
        ),
    ]
